### ISSUE TITLE
コメント削除機能

### ISSUE THREAD

**Issue by mather** [tegehoge/LeacTion#10]
自分のコメントを削除できるようにするべきか
要望があれば作ってもいいかも

**Comment by mather** [comment]
## アイデア

削除リクエストにコメントIDとハッシュ化前のユーザーIDを送るようにすれば、確実に自分のブラウザからコメントを削除していることが判別できそう

**Comment by koogawa** [comment]
アイデア：
Firebase Authentication で匿名ログインさせてしまう。
匿名ログイン済み、かつ、uid が一致した場合のみ削除できるようにする。
