### ISSUE TITLE
左上のロゴをタップしたらトップに遷移してほしい

### ISSUE THREAD

**Issue by koogawa** [tegehoge/LeacTion#32]
新しいイベントを作りたいなーと思ったとき、トップに戻る導線がないので、左上のロゴをタップしたらトップに遷移するのはどうでしょうか？

![image](https://user-images.githubusercontent.com/893643/98244625-14975080-1fb3-11eb-99df-5e9d9d91bb81.png)

**Comment by mather** [comment]
イベント開催中にページから離れる必要はないと思ったのでリンクを作ってませんでしたが、
次のイベント作成者に対してアプローチするにはリンクがあったほうが良さそうですね。

**Comment by koogawa** [comment]
たしかに「新しいイベントを作成する」は別にリンクを用意しても良さそうですね。

「新しいイベントを作りたい」という動機以外として、イベント画面に直接飛んできたユーザーがサイトの全体像を把握したいときにもトップへのリンクがあったほうが良いかなーと思いました。
「ロゴをタップしたらトップへ遷移する」という動きは他のサイトでもよくあるので、ユーザ体験としても自然だと思うんですよね！

**Comment by mather** [comment]
> イベント画面に直接飛んできたユーザーがサイトの全体像を把握したいときにもトップへのリンクがあったほうが良いかなーと思いました。

イベントに参加している時点ではこれ以外のページに行っても元のイベントへ戻る方法がないんですよね…。（現状はURLのみの公開のため、トップページに開催中のイベント一覧などがない）

> 「ロゴをタップしたらトップへ遷移する」という動きは他のサイトでもよくあるので、ユーザ体験としても自然だと思うんですよね！

トップページからのサイト内回遊が自然である場合は良いと思うのですが、トップページの用途が今の所は「新しいイベントを作る」以外にないので逆に迷うことになりそうな気がしています。

**Comment by koogawa** [comment]
わかりました！クローズします
